---

# create virtual enviroment for ansible, so python packages on which
# ansible needs can be installed, but don't mess up rest of the system.
# from https://medium.com/@crobin

- name: Install Ansible dependencies
  hosts: all
  become: true
  vars:
    # add here if necessary
    ansible_dependencies:
      - pip
  tasks:

    - name: Create deployment folder
      file: 
        path: /opt/ansible-deploy
        state: directory 
        mode: 0755

    - name: Install ansible dependencies
      package:
        name:
          - python3-apt
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
        state: present

    - name: Install python libraries
      pip:
        name: "{{ item }}"
        state: latest
        virtualenv: /opt/ansible-deploy
        virtualenv_site_packages: yes
      loop: "{{ ansible_dependencies }}"

    - name: Tell subsequent tasks to use our deploy virtualenv
      set_fact:
        ansible_python_interpreter: /opt/ansible-deploy/bin/python

- name: common basic provision
  hosts: all
  roles:
    - common

- name: provision of eve
  hosts: eve
  roles:
    - eve
    
- name: provision of alice
  hosts: alice
  roles:
    - alice

- name: povision of bob
  hosts: bob
  roles:
    - bob
...
