---

# create virtual enviroment for ansible, so python packages on which
# ansible needs can be installed, but don't mess up rest of the system.
# from https://medium.com/@crobin

- name: Install Ansible dependencies
  hosts: all
  become: true
  tags: ansible-setup
  vars:
    ansible_dependencies:
      - pip
  tasks:

    - name: Create deployment folder
      file: 
        path: /opt/ansible-deploy
        state: directory 
        mode: 0755

    - name: Install ansible dependencies
      package:
        name:
          - python3-apt
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
        state: present

    - name: Install python libraries
      pip:
        name: "{{ item }}"
        state: latest
        virtualenv: /opt/ansible-deploy
        virtualenv_site_packages: yes
      loop: "{{ ansible_dependencies }}"

    - name: Tell subsequent tasks to use our deploy virtualenv
      set_fact:
        ansible_python_interpreter: /opt/ansible-deploy/bin/python

- name: generate ssh key
  hosts: 127.0.0.1
  connection: local
  run_once: true
  tasks:
    - name: generate ssh key pair
      community.crypto.openssh_keypair:
        path: ~/.ssh/sandbox
      tags: ssh

- name: common basic provision
  hosts: all
  roles:
    - common

# ansible provisiones each host concurrently, but
# tasks in each role are still played linearly
- name: provision eve, alice and bob concurrently
  hosts: all
  strategy: free
  tasks:
  - name: provision eve
    include_role:
      name: eve
    when: inventory_hostname == "eve"
  - name: provision alice
    include_role:
      name: alice
    when: inventory_hostname == "alice"
  - name: provision bob
    include_role:
      name: bob
    when: inventory_hostname == "bob"
  tags: test

...
