---

- block:

    - name: update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.name }}"
      loop:
        - { ip: 10.10.10.2,  name: eve   }
        - { ip: 10.10.10.3,  name: alice }
        - { ip: 192.168.0.2, name: alice }
        - { ip: 192.168.0.3, name: bob   }

    - name: configure network interfaces
      copy:
        src: "netplan/50-ansible.yaml.{{ inventory_hostname }}"
        dest: /etc/netplan/50-ansible.yaml

    - name: bring up network interfaces
      shell: "netplan apply"

    - name: python symlink to python3
      file:
        path: /usr/bin/python
        src: /usr/bin/python3
        state: link

    - name: create user
      user:
        name: "{{ inventory_hostname }}"
        shell: /bin/bash
        groups: sudo
        password: "{{ 'password' | password_hash('sha512') }}"
      tags: user

    - name: clone my git dotfiles repo
      git:
        repo: http://github.com/chovanecadam/dotfiles.git
        dest: /opt/dotfiles

    - name: run setup.sh for "{{ inventory_hostname }}" 
      shell: "cd /opt/dotfiles && sudo bash /opt/dotfiles/setup.sh {{ inventory_hostname }} -q"
      tags: dotfiles

    - name: run setup.sh for root
      shell: "cd /opt/dotfiles && sudo bash /opt/dotfiles/setup.sh root -q"
      tags: dotfiles

    - name: add authorized key
      ansible.posix.authorized_key:
        user: "{{ inventory_hostname }}"
        key: "{{ lookup('file', '~/.ssh/sandbox.pub') }}"
      tags: ssh

    - name: copy private key
      copy:
        src: ~/.ssh/sandbox
        dest: "/home/{{ inventory_hostname }}/.ssh/id_rsa"
        owner: "{{ inventory_hostname }}"
        group: "{{ inventory_hostname }}"
        mode: 0600
      tags: ssh

  become: yes

# block only for Alice and Bob
- block:
    - name: create http directory
      file:
        path: /srv/http
        state: directory
        owner: vagrant
        group: vagrant
      tags: http-server

    - name: start python server
      shell: 
        cmd: "nohup python -m http.server --bind 127.0.0.1 --directory /srv/http 80 </dev/null >/dev/null 2>&1 &"
      tags: http-server

    - name: disconnect from the internet
      command: "ip route del default"

  become: yes
  when: inventory_hostname == "alice" or inventory_hostname == "bob"
...
