---

- block:

    - name: index.html
      lineinfile:
        path: /srv/http/index.html
        line: "Website reachable only from Bob's localhost"
        create: yes
        owner: vagrant
        group: vagrant
      tags: http-server

  become: yes


...
