---

- block:

    - name: index.html
      lineinfile:
        path: /srv/http/index.html
        line: "Website reachable only from Bob's localhost"
        create: yes

    - name: add route to eve
      command: "ip route add 10.10.10.0/24 via 192.168.0.2"

  become: yes


...
