---

- block: 

    - name: index.html
      lineinfile:
        path: /srv/http/index.html
        line: "Website reachable only from Alice's localhost"
        create: yes
        owner: vagrant
        group: vagrant
      tags: http-server

    - name: enable routing on alice
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

  become: yes
...
